### ISSUE TITLE
there is no "train_esm.npy" under the path "../data/" 

### ISSUE THREAD

**Issue by ShugangZhang** [yzh9607/TransEFVP#1]
Hi team, could you tell us how to generate the train_esm.npy? The training script cannot run without this file. Thanks!

**Comment by yzh9607** [comment]
This file can be obtained through getEsm.py, and data can be generated according to your specific needs with simple operations.


&nbsp;Best wishes
&nbsp;
------------------ Original ------------------
From: &nbsp;"Shugang ***@***.***&gt;;
Date: &nbsp;Fri, Mar 1, 2024 07:14 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[yzh9607/TransEFVP] there is no "train_esm.npy" under the path "../data/"  (Issue #1)

&nbsp;



 
Hi team, could you tell us how to generate the train_esm.npy? The training script cannot run without this file. Thanks!

**Comment by ShugangZhang** [comment]
谢谢回复！你们的工作非常棒，我也大致知道怎么来复现，就是有两个细节确实不太明确，还请您多多指教。

1、您的模型的第一阶段的输出（Fig.1b）的分数，怎么定义呢，是不是就是直接定义BLB=0，PLP=1，然后把这个阶段转为回归问题？
2、您的基线模型E-SNPs&GO放出来的数据库里，training_set.tsv的第四列是一个0-10的整数，但是没交代这个数是什么。请问你们是怎么处理的这个数呢？

还请您百忙之中回复，非常感谢！

**Comment by yzh9607** [comment]
感谢您对我们的工作感兴趣


1、是的，模型的第一阶段可以理解为单独的回归问题来比较性能，把其中的concatenate层提出作为第二阶段的输入
2、E-SNPs&amp;GO数据中training_set.tsv的第四列为单独计算的置信度，具体信息可以参考原文，原文链接：https://doi.org/10.1093/bioinformatics/btac678
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Mar 4, 2024 08:47 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [yzh9607/TransEFVP] there is no "train_esm.npy" under the path "../data/"  (Issue #1)

&nbsp;



 
谢谢回复！你们的工作非常棒，我也大致知道怎么来复现，就是有两个细节确实不太明确，还请您多多指教。
 
1、您的模型的第一阶段的输出（Fig.1b）的分数，怎么定义呢，是不是就是直接定义BLB=0，PLP=1，然后把这个阶段转为回归问题？
 2、您的基线模型E-SNPs&amp;GO放出来的数据库里，training_set.tsv的第四列是一个0-10的整数，但是没交代这个数是什么。请问你们是怎么处理的这个数呢？
 
还请您百忙之中回复，非常感谢！

**Comment by ShugangZhang** [comment]
明白，谢谢作者答复！
